version: "3.5"

services:
  api01: &api
    image: luc4skr/rinha-de-backend:202403092244
    hostname: api01
    environment:
      - DB_HOSTNAME=db
      - DB_CONNECTION_STRING=Host=db;Username=admin;Password=123;Database=rinha;Minimum Pool Size=10;Maximum Pool Size=10;Multiplexing=true;Application Name=RinhaDeBackendDotnet
    
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "200MB"

  api02:
    <<: *api 
    hostname: api02
    environment:
      - DB_HOSTNAME=db
      - DB_CONNECTION_STRING=Host=db;Username=admin;Password=123;Database=rinha;Minimum Pool Size=10;Maximum Pool Size=10;Multiplexing=true;Application Name=RinhaDeBackendDotnet
    ports:
      - "8082:8080"
 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "140MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx