version: "3.5"
services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    deploy:
      resources:
        limits:
          cpus: "0.05"
          memory: "0.4GB"
  
  api01: &api
    image: lucaskr/rinha-api-2024
    hostname: rinha-api01
    depends_on:
      - db
    environment:
      - DB_CONNECTION_STRING=Host=db;Username=admin;Password=123;Database=rinha;Connection Pruning Interval=1;Connection Idle Lifetime=2;
      - _DB_CONNECTION_STRING=Host=db;Username=admin;Password=123;Database=rinha;
      - DOTNET_GCConserveMemory=1
      - DOTNET_gcServer=1
      - DOTNET_gcConcurrent=0
      - _DOTNET_GCHeapCount=0x1
      - _DOTNET_GCNoAffinitize=1
      - _DOTNET_GCHeapHardLimitPercent=0x10
    ports:
      - "8081:80"
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: "0.568"
          memory: "1.0GB"
  
  api02:
    <<: *api
    ports:
      - "8082:80"
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "0.1GB"

networks:
  default:
    driver: bridge
    name: rinha
